---
- name: Configure Redis Cluster
  hosts: redis_nodes
  become: yes
  gather_facts: yes
  vars:
    ansible_ssh_private_key_file: "./redis-infra-key.pem"
    ansible_ssh_user: ubuntu
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o ConnectTimeout=30
      -o ServerAliveInterval=60
      -o ServerAliveCountMax=3
      {% if bastion_host is defined %}
      -o ProxyCommand="ssh -W %h:%p -i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=no -o ConnectTimeout=30 ubuntu@{{ bastion_host }}"
      {% endif %}
  
  pre_tasks:
    - name: Wait for system to become reachable
      wait_for_connection:
        connect_timeout: 30
        timeout: 300
    
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      retries: 3
      delay: 10
  
  tasks:
    - name: Install Redis packages
      apt:
        name:
          - redis-server
          - redis-tools
        state: present
        update_cache: yes
      retries: 3
      delay: 10
    
    - name: Stop Redis service for configuration
      service:
        name: redis-server
        state: stopped
    
    - name: Configure Redis for clustering
      lineinfile:
        path: /etc/redis/redis.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backup: yes
      loop:
        - { regexp: '^bind ', line: 'bind 0.0.0.0' }
        - { regexp: '^# cluster-enabled ', line: 'cluster-enabled yes' }
        - { regexp: '^# cluster-config-file ', line: 'cluster-config-file nodes-6379.conf' }
        - { regexp: '^# cluster-node-timeout ', line: 'cluster-node-timeout 15000' }
        - { regexp: '^appendonly ', line: 'appendonly yes' }
        - { regexp: '^protected-mode ', line: 'protected-mode no' }
      notify: restart redis
    
    - name: Start and enable Redis service
      service:
        name: redis-server
        state: started
        enabled: yes
    
    - name: Wait for Redis to be ready
      wait_for:
        port: 6379
        host: "{{ ansible_default_ipv4.address }}"
        delay: 5
        timeout: 60
    
    - name: Test Redis connectivity
      command: redis-cli -h {{ ansible_default_ipv4.address }} ping
      register: redis_ping
      retries: 5
      delay: 3
      until: redis_ping.stdout == "PONG"
    
    - name: Display Redis status
      debug:
        msg: "Redis is running on {{ ansible_default_ipv4.address }}:6379"
  
  handlers:
    - name: restart redis
      service:
        name: redis-server
        state: restarted
      listen: restart redis
